INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	5	,	100	,	18	,	18	,'	Director Administrativo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	24	,	4	,	4	,'	Portero - Casero	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	2	,	4	,	4	,'	Cocinero	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	15	,	3	,	5	,'	Mucama	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	8	,	1	,	4	,	7	,'	Director General	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	5	,	100	,	16	,	16	,'	Jefe de Departamento	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	5	,	100	,	12	,	12	,'	Jefe de División	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	10	,	4	,	4	,'	Guardián	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	17	,	2	,	6	,'	Ordenanza "B"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	197	,	3	,	0	,'	Asistente de Casa Estudiantil	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	75	,	6	,	0	,'	Ayudante de Mantenimiento	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	16	,	2	,	0	,'	Auxiliar Técnico de Obras "B"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	6	,	4	,	4	,'	Chofer "B"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	20	,	3	,	0	,'	Encargado de Conmutador Telefónico	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	21	,	5	,	5	,'	Operador de Conmutador Telefónico	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	39	,	2	,	0	,'	Oficial Contable	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	40	,	3	,	0	,'	Auxiliar Contable	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	50	,	2	,	0	,'	Dibujante "A"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	110	,	1	,	0	,'	Sistemas de Computación de Datos - Programador "A"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	111	,	2	,	0	,'	Sistemas de Computación de Datos - Programador "B"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	11	,	1	,	0	,'	Arquitecto "A"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	21	,	15	,	2	,'	Contador "B"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	77	,	2	,	0	,'	Ingeniero Forestal "B"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	8	,	2	,	4	,	0	,'	Secretario General	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	7	,	2	,	5	,	2	,'	Subsecretario	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	7	,	1	,	3	,	1	,'	Ministro	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	98	,	3	,	0	,'	Investigador Científico "C	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	47	,	2	,	0	,'	Oficial "A" de Depósitos y Almacenes	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	36	,	3	,	0	,'	Auxiliar de Compras	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	51	,	6	,	3	,'	Dibujante "B"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	66	,	2	,	0	,'	Inspector de Recursos Naturales	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	105	,	3	,	0	,'	Sistemas de Computación de Datos - Analista "C"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	16	,	3	,	5	,'	Ordenanza "A"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	18	,	2	,	6	,'	Peón	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	13	,	9	,	3	,'	Capataz de Talleres Menores	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	111	,	5	,	0	,'	Costurera	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	17	,	3	,	0	,'	Auditor de Prestaciones Médicas	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	80	,	3	,	0	,'	Oficial Especializado en Cultivos	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	16	,	5	,	0	,'	Carpintero - Medio Oficial	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	15	,	1	,	0	,'	Auxiliar Técnico de Obras "A"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	37	,	4	,	0	,'	Ayudante de Compras	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	29	,	6	,	3	,'	Chofer de Establecimiento Educativo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	5	,	6	,	3	,'	Chofer "A"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	7	,	3	,	5	,	2	,'	Subsecretario	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	3	,	3	,	5	,'	Ayudante de Cocina	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	4	,	2	,	4	,'	Correo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	19	,	3	,	5	,'	Portero de Escuela	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	4	,	4	,	4	,'	Ayudante Administrativo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	79	,	7	,	4	,'	Medio Oficial de Oficios Varios	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	2	,	5	,	5	,'	Medio Oficial Albañil	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	3	,	11	,	3	,'	Abogado "C"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	1	,	7	,	4	,'	Albañil	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	105	,	6	,	0	,'	Sistemas de Computación de Datos - Analista "C"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	166	,	6	,	3	,'	Asistente Infantil	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	3	,	6	,	3	,'	Auxiliar Administrativo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	9	,	3	,	6	,'	Canalero	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	15	,	7	,	4	,'	Carpintero	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	1	,	6	,	3	,'	Cocinero de Residencia	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	20	,	17	,	1	,'	Contador "A"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	111	,	5	,	5	,'	Costurera	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	32	,	7	,	4	,'	Encuadernador	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	40	,	7	,	4	,'	Foguista Encargado	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	65	,	3	,	6	,'	Jardinero	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	22	,	3	,	5	,'	Lavadero - Planchador	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	12	,	6	,	3	,'	Encargado de Maestranza	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	13	,	8	,	2	,'	Mayordomo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	2	,	10	,	2	,'	Oficial Administrativo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	81	,	7	,	4	,'	Oficial de Cultivo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	78	,	9	,	3	,'	Oficial de Oficios Varios	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	1	,	14	,	1	,'	Oficial Superior Administrativo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	2	,	15	,	2	,'	Personal Profesional Cat. 15	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	1	,	17	,	1	,'	Personal Profesional Cat. 17	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	131	,	10	,	2	,'	Técnico en Mantenimiento "A"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	115	,	4	,	0	,'	Sistemas de Computación de Datos - Operador "C"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	29	,	5	,	0	,'	Electricista Instalador - Medio Oficial	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	21	,	6	,	0	,'	UTILERO	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	21	,	7	,	0	,'	Operador de Conmutador Telefónico	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	138	,	17	,	0	,'	TECNOLOGO CLASE "A"	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	8	,	5	,	9	,	0	,'	SECRETARIO DE MINISTRO	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	0	,	0	,	1	,	0	,'	Planta Transitoria	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	1	,	2	,	0	,'	Personal de Servicio	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	1	,	3	,	0	,'	Personal de Servicio	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	1	,	1	,	4	,	0	,'	Personal de Servicio	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	1	,	1	,	0	,'	Personal Obrero	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	1	,	3	,	0	,'	Personal Obrero	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	2	,	1	,	4	,	0	,'	Personal Obrero	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	1	,	1	,	0	,'	Personal Administrativo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	1	,	12	,	0	,'	Jefe de División	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	1	,	16	,	0	,'	Jefe de Departamento	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	1	,	2	,	0	,'	Personal Administrativo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	1	,	3	,	0	,'	Personal Administrativo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	3	,	1	,	4	,	0	,'	Personal Administrativo	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	1	,	1	,	0	,'	Personal Profesional y Técnico	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	4	,	1	,	3	,	0	,'	Personal Profesional y Técnico	');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	7	,	4	,	5	,	0	,'		');
INSERT INTO snpe.cargosnds (  cargo_agrup, cargo_cod, cargo_categ, nivel, cargo_desc ) VALUES(	8	,	5	,	13	,	0	,'		');
