INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'001','	H	','	HORAS CÁTEDRAS- (PROFESOR)	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'001','	C	','	SUPERVISOR TÉCNICO GENERAL	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'002','	H	','	HORAS CÁTEDRAS-  (PROFESOR)	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'002','	C	','	SUPERVISOR TÉCNICO SECCIONAL	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'003','	C	','	SECRETARIO TÉCNICO GENERAL	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'004','	C	','	DIRECTOR DE ESC.PERF.DOCENTE	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'015','	C	','	SUPERVISOR ESCOLAR DE MATERIAS  ESPECIALES	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'019','	C	','	GABINETE CON 35 HORAS SEMANALES	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'020','	C	','	GABINETE CON 20 HORAS SEMANALES	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'101','	C	','	SUPERVISOR ESCOLAR	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'104','	C	','	VICEDIRECTOR JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'106','	C	','	DIRECTOR PRIM.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'107','	C	','	DIRECTOR SEGUN.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'108','	C	','	VICEDIRECTOR ESC. COMUN	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'110','	C	','	DIRECTOR TERC.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'111','	C	','	MAESTRO DE AÑO	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'112','	C	','	MAESTRO ESPECIAL	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'113','	C	','	MAESTRO BILIOTECARIO	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'114','	C	','	DIRECTOR DE BIBLIOTECA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'115','	C	','	MAESTRO DE AÑO 3° CICLO  EGB	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'116','	C	','	MAESTRO SECRETARIO	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'117','	C	','	MAESTRO ESPECIAL ESC. COMUN  12 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'118','	C	','	MAESTRO ESPECIAL ESC. COMUN  15 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'119','	C	','	MAESTRO ESPECIAL ESC. COMUN  18 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'201','	C	','	SUPERVISOR ESCOLAR	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'206','	C	','	DIRECTOR PRIM.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'207','	C	','	DIRECTOR SEGUN.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'208','	C	','	VICEDIRECTOR	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'210','	C	','	DIRECTOR TERC.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'211','	C	','	MAESTRO DE AÑO	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'212','	C	','	MAESTRO ESPECIAL 18 HORAS	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'217','	C	','	MAESTRO ESPECIAL ESC. INT. ALB.  12 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'218','	C	','	MAESTRO ESPECIAL ESC. INT. ALB.  15 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'219','	C	','	MAESTRO ESPECIAL ESC. INT. ALB.  18 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'305','	C	','	DIRECTOR PRIM.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'306','	C	','	DIRECTOR PRIM.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'307','	C	','	DIRECTOR SEGUN.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'308','	C	','	VICEDIRECTOR  ESC. JORN. COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'310','	C	','	DIRECTOR TERC.CATEG. ESC. JORN. COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'311','	C	','	MAESTRO DE AÑO JORNADA COMPLETA	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'312','	C	','	MAESTRO ESPECIAL 15 HORAS	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'313','	C	','	MAESTRO DE ORIENTACION Y TUTORIA	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'314','	C	','	VICEDIRECTOR DE 3° CICLO EGB	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'315','	C	','	M.DE AÑO 3° CICLO  JORN COMPL.	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'317','	C	','	MAESTRO ESPECIAL ESC. JOR. COMP.  12 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'318','	C	','	MAESTRO ESPECIAL ESC. JOR. COMP.  15 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'319','	C	','	MAESTRO ESPECIAL ESC. JOR. COMP.  18 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'320','	C	','	MAESTRO DE ORIENT. Y TUT.  3° ciclo J/C	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'321','	C	','	DIRECTOR SEGUN.CATEG.JORN. COMP. 7 hs.	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'322','	C	','	DIRECTOR TERC.CATEG. ESC. JORN. COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'501','	C	','	SUPERVISOR ESCOLAR	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'502','	C	','	DIRECTOR PRIM.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'503','	C	','	DIRECTOR SEGUN.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'505','	C	','	DIRECTOR TERC.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'506','	C	','	DIRECTOR PRIM.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'507','	C	','	DIRECTOR SEGUN.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'508','	C	','	VICEDIRECTOR	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'510','	C	','	DIRECTOR TERC.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'511','	C	','	MAESTRO DE AÑO	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'512','	C	','	MAESTRO ESPECIAL	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'515','	C	','	MAESTRO DE A. 3 ° CICLO	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'517','	C	','	MAESTRO ESPECIAL ESC. HOSP. Y DOM. 12 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'518','	C	','	MAESTRO ESPECIAL ESC. HOSP. Y DOM.  15 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'519','	C	','	MAESTRO ESPECIAL ESC. HOSP. Y DOM. 18 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'601','	C	','	SUPERVISOR ESCOLAR	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'602','	C	','	DIRECTOR PRIM.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'603','	C	','	DIRECTOR SEGUN.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'605','	C	','	DIRECTOR TERC.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'606','	C	','	DIRECTOR PRIM.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'607','	C	','	DIRECTOR SEGUN.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'627','	C	','	DIRECTOR SEGUN.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'608','	C	','	VICEDIRECTOR	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'610','	C	','	DIRECTOR TERC.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'611','	C	','	MAESTRO DE AÑO	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'612','	C	','	MAESTRO ESPECIAL	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'617','	C	','	MAESTRO ESPECIAL ESC. ADULTOS 12 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'618','	C	','	MAESTRO ESPECIAL ESC. ADULTOS 15 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'619','	C	','	MAESTRO ESPECIAL ESC. ADULTOS 18 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'701','	C	','	SUPERVISOR ESCOLAR	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'702','	C	','	DIRECTOR DE PRIM.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'703','	C	','	DIRECTOR DE SEGUN.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'705','	C	','	DIRECTOR DE TERC.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'708','	C	','	VICEDIRECTOR  ESC. ESP.	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'709','	C	','	MAESTRO DE AÑO JORNADA COMPLETA ESPECIAL	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'711','	C	','	MAESTRO DE AÑO ESC. ESP.	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'712','	C	','	MAESTRO ESPECIAL ESC. ESP.	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'717','	C	','	MAESTRO ESPECIAL ESC. ESP.  12 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'718','	C	','	MAESTRO ESPECIAL ESC. ESP.  15 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'719','	C	','	MAESTRO ESPECIAL ESC. ESP.  18 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'801','	C	','	SUPERVISOR ESCOLAR NIVEL INICIAL	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'802','	C	','	DIRECTOR DE PRIM.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'803','	C	','	DIRECTOR DE SEGUN.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'805','	C	','	DIRECTOR DE TERC.CATEG.JORNADA COMPLETA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'806','	C	','	DIRECTOR DE PRIM.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'807','	C	','	DIRECTOR DE SEGUN.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'827','	C	','	DIRECTOR DE SEGUN.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'808','	C	','	VICEDIRECTOR	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'809','	C	','	M.DE AÑO JORN. COMPL. NIVEL INICIAL	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'810','	C	','	DIRECTOR DE TERC.CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'811','	C	','	MAESTRO DE AÑO	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'812','	C	','	MAESTRO ESPECIAL	',	1	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'817','	C	','	MAESTRO ESPECIAL NIVEL INICIAL 12 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'818','	C	','	MAESTRO ESPECIAL NIVEL INICIAL 15 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'819','	C	','	MAESTRO ESPECIAL NIVEL INICIAL 18 HS.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'904','	C	','	SUPERVISOR GENERAL/ SECRET. TEC. GRAL.	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'907','	C	','	SUPERVISOR TÉCNICO	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'913','	C	','	DIRECTOR DE PRIMERA CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'914','	C	','	DIRECTOR DE SEGUNDA CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'915','	C	','	DIRECTOR DE TERCERA CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'916','	C	','	VICEDIRECTOR DE PRIMERA CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'917','	C	','	VICEDIRECTOR DE SEGUNDA CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'918','	C	','	VICEDIRECTOR DE TERCERA CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'919','	C	','	REGENTE DE PRIMERA CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'920','	C	','	REGENTE DE SEGUNDA CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'921','	C	','	REGENTE DE TERCERA CATEGORIA	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'925','	C	','	JEFE GRAL.DE ENSEÑANZA PRACTICA -1era.	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'926','	C	','	JEFE GRAL.DE ENSEÑANZA PRACTICA -2da.	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'927','	C	','	JEFE GRAL.DE ENSEÑANZA PRACTICA -3era.	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'928','	C	','	SECRETARIO DE PRIMERA CATEG.	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'929','	C	','	SECRETARIO DE SEGUNDA CATEG.	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'930','	C	','	SECRETARIO DE TERCERA CATEG.	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'934','	C	','	MAESTRO DE ENS.PRACT.JEFE SECCIÓN	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'935','	C	','	MAESTRO DE ENS.PRACT.	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'943','	C	','	BIBLIOTECARIO	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'944','	C	','	PRECEPTOR	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'954','	C	','	Resp. Bibliotecario	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'956','	C	','	Coord. Politicas	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'957','	C	','	Coord. Linea	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'958','	C	','	Coord. Anexo	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'959','	C	','	Resp. Centro	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'960','	C	','	PROFESOR DE ENS. PRACTICAS -- 16H (ESC. TRANSF.)	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'961','	C	','	PROFESOR DE ENS. PRACTICAS -- 18H (ESC. TEC.)	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'962','	C	','	PROFESOR DE ENS. PRACTICAS -- 20H (ESC. AGROTEC.)	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'963','	C	','	PEP -- CENTRO FORM. PROFESIONAL -- 16HS	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'964','	C	','	PEP -- CENTRO FORM. PROFESIONAL -- 20HS	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'965','	C	','	PEP -- CERET -- 20HS	',	3	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'967','	C	','	ADMINISTRADOR DE REDES -- 20HS	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'966','	C	','	PROFESOR DE LABORATORIO (20HS)	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'955','	C	','	Bedel IES	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'950','	C	','	Director ISFD	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'951','	C	','	Vice. Director ISFD	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'952','	C	','	Secretario AC	',	2	);
INSERT INTO snpe.funcions (categoria, tipo_cargo, descripcion, grupo) VALUES(	'953','	C	','	Secretario ad.	',	2	);
