#-- BASE DEL PROYECTO DATABASE --#
  development:
    adapter: mysql2
    encoding: utf8
    database: proyecto-base-bs3
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
#    
  test:
    adapter: mysql2
    encoding: utf8
    database: proyecto-base-bs3
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
#    
  production:
    adapter: mysql2
    encoding: utf8
    database: proyecto-base-bs3
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
